
services:
  - type: web
    name: vet-clinic
    runtime: python
    region: frankfurt 
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput
      python manage.py seed_data
      gunicorn vet_clinic.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: vetclinic-db
          property: connectionString
    autoDeploy: true
    plan: free

databases:
  - name: vetclinic-db
    databaseName: vetclinic
    user: vetclinic_user
    plan: free
    region: frankfurt